# Generated by Django 3.2.23 on 2023-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='gender',
            field=models.CharField(choices=[('MIX', 'Mixed'), ('MEN', 'Men'), ('WOM', 'Women')], default='MIX', max_length=3),
        ),
    ]
