# Generated by Django 4.2.7 on 2023-11-12 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vfun", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
    ]
