# Generated by Django 3.2.23 on 2023-12-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfun', '0002_session_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('datetime',)},
        ),
        migrations.RenameField(
            model_name='sportshall',
            old_name='hall_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfun_session', to='vfun.sportshall'),
        ),
        migrations.AlterField(
            model_name='session',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfun_organized_session', to='vfun.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(related_name='vfun_joined_session', to='vfun.Profile'),
        ),
        migrations.AlterField(
            model_name='sportshall',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vfun_sportshall', to='vfun.profile'),
        ),
    ]
