# Generated by Django 3.2.23 on 2023-12-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfun', '0004_alter_session_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='vfun_joined_session', to='vfun.Profile'),
        ),
    ]
