# Generated by Django 3.2.23 on 2023-12-26 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfun', '0005_alter_session_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='vfun.sportshall'),
        ),
        migrations.AlterField(
            model_name='session',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_sessions', to='vfun.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='joined_sessions', to='vfun.Profile'),
        ),
        migrations.AlterField(
            model_name='sportshall',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sportshalls', to='vfun.profile'),
        ),
    ]
